== someone posted patch, how to add it to repository

Let's assume the patch is for games repo.

clone repo as described here https://galileo.mailstation.de/?p=225

create new branch in repo, apply patch http://ariejan.net/2009/10/26/how-to-create-and-apply-a-patch-with-git/

----
git apply some.patch
----

Add info about your local repo to /etc/paludis/repositories/games.conf http://exherbo.org/docs/workflow.html

----
format = e
location = /var/db/paludis/repositories/games
sync = git://git.exherbo.org/games.git local: git+file:///home/rfrolow/projects/exherbo/games
sync_options = --branch=master local: --branch=ioquake3
----

Add any new categories that were added by patch to /path/to/loca/games/metadata/categories.conf

Sync your changes with paludis

----
cave sync --suffix local games
----

== build fails

09:48:46          qu7uux | Philantrop: are the build failures in what I just commited because I separated the licence needed by 662 ?
10:00:15      Guest22754 | qu7uux: It seems so. commit those two packages together
10:03:54          rofrol | qu7uux: If you look at jenkins log, you can see it yourself: Found no packages ...
10:05:28           nicoo | Guest58216: It isn't apparent that commiting both exhereses together would solve anything.
10:06:12           nicoo | qu7uux: By the way, if you use git-review, sending a branch for review creates one proposal per commit, with each commit depending on the previous ones.
